default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: admin
  port: 5432

development:
  <<: *default
  database: twitter_clone_development
  host: localhost
  username: postgres
  password: admin
  port: 5432

# test:
#   <<: *default
#   username: postgres
#   password: admin


# production:
#   <<: *default
#   username: postgres
#   password: admin
